# Generated by Django 2.0.2 on 2018-03-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Predmety',
            new_name='Predmet',
        ),
    ]
